# Generated by Django 5.2.5 on 2025-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dgmvyic4g/image/upload/v1/default.png'),
        ),
    ]
