# Generated by Django 5.2.5 on 2025-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dgmvyic4g/image/upload/v1/default.png'),
        ),
    ]
