# Generated by Django 5.2.5 on 2025-08-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_slug_alter_category_name'),
        ('blog', '0007_add_category_slug_safely'),
    ]

    operations = [
    ]
